// BOOKINGS REDUCER
export const GET_BOOKINGS_SUCCESS = 'GET_BOOKINGS_SUCCESS'
export const GET_BOOKINGS_FAIL = 'GET_BOOKINGS_FAIL'

export const CREATE_BOOKING_REQUEST = 'CREATE_BOOKING_REQUEST'
export const CREATE_BOOKING_SUCCESS = 'CREATE_BOOKING_SUCCESS'
export const CREATE_BOOKING_FAIL = 'CREATE_BOOKING_FAIL'

export const UPDATE_BOOKING_REQUEST = 'UPDATE_BOOKING_REQUEST'
export const UPDATE_BOOKING_SUCCESS = 'UPDATE_BOOKING_SUCCESS'
export const UPDATE_BOOKING_FAIL = 'UPDATE_BOOKING_FAIL'

export const CLEAR_BOOKINGS_SUCCESS = 'CLEAR_BOOKINGS_SUCCESS'
export const CLEAR_BOOKINGS_ERRORS = 'CLEAR_BOOKINGS_ERRORS'


// CACHE BOOKING DATA REDUCER
export const CACHE_BOOKING_DATA = 'CACHE_BOOKING_DATA'


// CREATE STRIPE PAYMENT INTENT REDUCER
export const CREATE_STRIPE_PAYMENT_INTENT_REQUEST = 'CREATE_STRIPE_PAYMENT_INTENT_REQUEST'
export const CREATE_STRIPE_PAYMENT_INTENT_SUCCESS = 'CREATE_STRIPE_PAYMENT_INTENT_SUCCESS'
export const CREATE_STRIPE_PAYMENT_INTENT_FAIL = 'CREATE_STRIPE_PAYMENT_INTENT_FAIL'
export const CLEAR_STRIPE_PAYMENT_INTENT_ERRORS = 'CLEAR_STRIPE_PAYMENT_INTENT_ERRORS'
