export const CREATE_STRIPE_PAYMENT_INTENT_REQUEST = 'CREATE_STRIPE_PAYMENT_INTENT_REQUEST'
export const CREATE_STRIPE_PAYMENT_INTENT_SUCCESS = 'CREATE_STRIPE_PAYMENT_INTENT_SUCCESS'
export const CREATE_STRIPE_PAYMENT_INTENT_FAIL = 'CREATE_STRIPE_PAYMENT_INTENT_FAIL'

export const CACHE_BOOKING_DATA = 'CACHE_BOOKING_DATA'

export const CREATE_BOOKING_REQUEST = 'CREATE_BOOKING_REQUEST'
export const CREATE_BOOKING_SUCCESS = 'CREATE_BOOKING_SUCCESS'
export const CREATE_BOOKING_FAIL = 'CREATE_BOOKING_FAIL'

export const ALL_BOOKINGS_SUCCESS = 'ALL_BOOKINGS_SUCCESS'
export const ALL_BOOKINGS_FAIL = 'ALL_BOOKINGS_FAIL'

export const UPDATE_BOOKING_REQUEST = 'UPDATE_BOOKING_REQUEST'
export const UPDATE_BOOKING_SUCCESS = 'UPDATE_BOOKING_SUCCESS'
export const UPDATE_BOOKING_FAIL = 'UPDATE_BOOKING_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'