export const CREATE_STRIPE_PAYMENT_INTENT_REQUEST = 'CREATE_STRIPE_PAYMENT_INTENT_REQUEST'
export const CREATE_STRIPE_PAYMENT_INTENT_SUCCESS = 'CREATE_STRIPE_PAYMENT_INTENT_SUCCESS'
export const CREATE_STRIPE_PAYMENT_INTENT_FAIL = 'CREATE_STRIPE_PAYMENT_INTENT_FAIL'

export const CACHE_BOOKING_DATA = 'CACHE_BOOKING_DATA'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'