export const ALL_EXPERTISE_POSTS_SUCCESS = 'ALL_EXPERTISE_POSTS_SUCCESS'
export const ALL_EXPERTISE_POSTS_FAIL = 'ALL_EXPERTISE_POSTS_FAIL'

export const EXPERTISE_POST_DETAIL_SUCCESS = 'EXPERTISE_POST_DETAIL_SUCCESS'
export const EXPERTISE_POST_DETAIL_FAIL = 'EXPERTISE_POST_DETAIL_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'