export const EXPERTISE_POST_DETAIL_SUCCESS = 'EXPERTISE_POST_DETAIL_SUCCESS'
export const EXPERTISE_POST_DETAIL_FAIL = 'EXPERTISE_POST_DETAIL_FAIL'

export const CREATE_EXPERTISE_POST_REQUEST = 'CREATE_EXPERTISE_POST_REQUEST'
export const CREATE_EXPERTISE_POST_SUCCESS = 'CREATE_EXPERTISE_POST_SUCCESS'
export const CREATE_EXPERTISE_POST_FAIL = 'CREATE_EXPERTISE_POST_FAIL'

export const UPDATE_EXPERTISE_POST_REQUEST = 'UPDATE_EXPERTISE_POST_REQUEST'
export const UPDATE_EXPERTISE_POST_SUCCESS = 'UPDATE_EXPERTISE_POST_SUCCESS'
export const UPDATE_EXPERTISE_POST_FAIL = 'UPDATE_EXPERTISE_POST_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'