export const CREATE_REVIEW_REQUEST = 'CREATE_REVIEW_REQUEST'
export const CREATE_REVIEW_SUCCESS = 'CREATE_REVIEW_SUCCESS'
export const CREATE_REVIEW_FAIL = 'CREATE_REVIEW_FAIL'

export const POST_REVIEWS_SUCCESS = 'POST_REVIEWS_SUCCESS'
export const POST_REVIEWS_FAIL = 'POST_REVIEWS_FAIL'

export const ALL_REVIEWS_SUCCESS = 'ALL_REVIEWS_SUCCESS'
export const ALL_REVIEWS_FAIL = 'ALL_REVIEWS_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'