export const CREATE_REVIEW_REQUEST = 'CREATE_REVIEW_REQUEST'
export const CREATE_REVIEW_SUCCESS = 'CREATE_REVIEW_SUCCESS'
export const CREATE_REVIEW_FAIL = 'CREATE_REVIEW_FAIL'

export const ALL_REVIEWS_SUCCESS = 'ALL_BOOKINGS_SUCCESS'
export const ALL_REVIEWS_FAIL = 'ALL_BOOKINGS_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'