export const REGISTER_USER_REQUEST = "REGISTER_USER_REQUEST";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_FAIL = "REGISTER_USER_FAIL";

export const LOAD_USER_REQUEST = "LOAD_USER_REQUEST";
export const LOAD_USER_SUCCESS = "LOAD_USER_SUCCESS";
export const LOAD_USER_FAIL = "LOAD_USER_FAIL";

export const UPDATE_USER_PROFILE_REQUEST = "UPDATE_USER_PROFILE_REQUEST";
export const UPDATE_USER_PROFILE_SUCCESS = "UPDATE_USER_PROFILE_SUCCESS";
export const UPDATE_USER_PROFILE_RESET = "UPDATE_USER_PROFILE_RESET";
export const UPDATE_USER_PROFILE_FAIL = "UPDATE_USER_PROFILE_FAIL";

export const FORGOT_PASSWORD_REQUEST = "FORGOT_PASSWORD_REQUEST";
export const FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS";
export const FORGOT_PASSWORD_FAIL = "FORGOT_PASSWORD_FAIL";

export const RESET_PASSWORD_REQUEST = "RESET_PASSWORD_REQUEST";
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_FAIL = "RESET_PASSWORD_FAIL";

export const SETUP_PAYOUTS_LINK_REQUEST = "SETUP_PAYOUTS_LINK_REQUEST";
export const SETUP_PAYOUTS_LINK_SUCCESS = "SETUP_PAYOUTS_LINK_SUCCESS";
export const SETUP_PAYOUTS_LINK_FAIL = "SETUP_PAYOUTS_LINK_FAIL";

export const CHECK_STRIPE_ACCOUNT_FIELD_REQUEST = "CHECK_STRIPE_ACCOUNT_FIELD_REQUEST";
export const CHECK_STRIPE_ACCOUNT_FIELD_SUCCESS = "CHECK_STRIPE_ACCOUNT_FIELD_SUCCESS";
export const CHECK_STRIPE_ACCOUNT_FIELD_FAIL = "CHECK_STRIPE_ACCOUNT_FIELD_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
